name: Deploy Sphinx Documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: configuration
      uses: sphinx-notes/pages@v3
      with:
        publish: false
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        checkout: false
        publish: true
